import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#000000',
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 22,
  },
  scrollContent: {
    flexGrow: 1,
    paddingTop: 18,
    paddingBottom: 8,
  },
  headerGlow: {
    minHeight: 70,
    borderRadius: 24,
    borderWidth: 1.25,
    borderColor: 'rgba(255, 52, 52, 0.28)',
    backgroundColor: '#050505',
    flexDirection: 'row',
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    shadowColor: '#FF1414',
    shadowOpacity: 0.45,
    shadowRadius: 20,
    shadowOffset: {width: 0, height: 8},
    elevation: 12,
  },
  headerBackButton: {
    position: 'absolute',
    left: 18,
    top: 9,
    bottom: 9,
    justifyContent: 'center',
    zIndex: 2,
  },
  headerBackFrame: {
    height: 52,
    minWidth: 116,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1.25,
    borderColor: 'rgba(255, 52, 52, 0.28)',
    backgroundColor: '#070707',
    justifyContent: 'center',
    shadowColor: '#FF1414',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: {width: 0, height: 4},
    elevation: 6,
    transform: [{skewX: '-16deg'}],
  },
  headerBackInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{skewX: '16deg'}],
  },
  headerBackArrow: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    marginRight: 10,
  },
  headerBackLogoImage: {
    width: 72,
    height: 28,
  },
  headerTitleWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 146,
    pointerEvents: 'none',
  },
  logoButton: {
    width: 120,
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingVertical: 6,
  },
  logoImage: {
    width: 92,
    height: 34,
  },
  headerTitle: {
    flex: 1,
    color: '#FFFFFF',
    textAlign: 'center',
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  headerSpacer: {
    width: 120,
  },
  contentRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  contentColumn: {
    flexDirection: 'column',
  },
  leftColumn: {
    flex: 1,
    marginRight: 12,
  },
  centerColumn: {
    flex: 1.2,
    marginHorizontal: 12,
  },
  rightColumn: {
    flex: 1,
    marginLeft: 12,
  },
  stackedColumn: {
    marginLeft: 0,
    marginRight: 0,
    marginHorizontal: 0,
    marginBottom: 16,
  },
  columnSpacer: {
    height: 16,
  },
  panelShell: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: '#050505',
    padding: 14,
    shadowColor: '#000000',
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: {width: 0, height: 6},
    elevation: 8,
  },
  livePanelBody: {
    borderRadius: 18,
    overflow: 'hidden',
  },
  tabRow: {
    flexDirection: 'row',
    backgroundColor: '#090909',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: 6,
    marginBottom: 14,
  },
  tabButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  tabButtonActive: {
    backgroundColor: '#C91D24',
    borderColor: 'rgba(255,255,255,0.12)',
  },
  tabButtonIdle: {
    backgroundColor: '#0F0F0F',
    borderColor: 'rgba(255,255,255,0.08)',
  },
  tabLabel: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
});

export default styles;
