import {StyleSheet} from 'react-native';
import {DesignSystem} from 'theme/designSystem';

type Metrics = {
  width: number;
  height: number;
};

const createStyles = (design: DesignSystem, metrics: Metrics) => {
  const {spacing, font, radius, safeArea, border, control} = design;
  const isCompact = metrics.width < 560;

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: '#030304',
      overflow: 'hidden',
    },
    screenGlowTop: {
      position: 'absolute',
      top: -metrics.height * 0.16,
      right: -metrics.width * 0.24,
      width: metrics.width * 0.76,
      height: metrics.width * 0.76,
      borderRadius: metrics.width,
      backgroundColor: 'rgba(201,29,36,0.22)',
    },
    screenGlowBottom: {
      position: 'absolute',
      bottom: -metrics.height * 0.18,
      left: -metrics.width * 0.22,
      width: metrics.width * 0.68,
      height: metrics.width * 0.68,
      borderRadius: metrics.width,
      backgroundColor: 'rgba(255,255,255,0.045)',
    },
    keyboardLayer: {
      flex: 1,
      paddingTop: safeArea.top + spacing.xs,
      paddingBottom: safeArea.bottom,
    },
    header: {
      minHeight: control.headerHeight,
      marginHorizontal: spacing.md,
      paddingHorizontal: spacing.sm,
      borderRadius: radius.xl,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.12)',
      backgroundColor: 'rgba(8,8,11,0.96)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      columnGap: spacing.sm,
      shadowColor: '#C91D24',
      shadowOpacity: 0.24,
      shadowOffset: {width: 0, height: 12},
      shadowRadius: spacing.lg,
      elevation: 14,
    },
    backButton: {
      minWidth: isCompact ? 88 : 110,
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.14)',
      backgroundColor: 'rgba(255,255,255,0.06)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.sm,
    },
    backText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    headerTitleWrap: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    title: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
      textAlign: 'center',
    },
    subtitle: {
      color: 'rgba(255,255,255,0.58)',
      fontSize: font.small,
      fontWeight: '800',
      marginTop: spacing.xxs,
      textAlign: 'center',
    },
    headerSpacer: {
      width: isCompact ? 88 : 110,
    },
    notice: {
      marginHorizontal: spacing.md,
      marginTop: spacing.sm,
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(0, 201, 94, 0.32)',
      backgroundColor: 'rgba(0, 201, 94, 0.13)',
      padding: spacing.sm,
    },
    noticeText: {
      color: '#D8FFF5',
      fontSize: font.body,
      fontWeight: '800',
    },
    body: {
      flex: 1,
      marginTop: spacing.md,
    },
    bodyContent: {
      paddingHorizontal: spacing.md,
      paddingBottom: spacing.xl,
      rowGap: spacing.sm,
    },
    emptyState: {
      borderRadius: radius.xl,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(255,255,255,0.055)',
      paddingVertical: spacing.xl,
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyIcon: {
      fontSize: font.title * 1.4,
      marginBottom: spacing.xs,
    },
    emptyText: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
      textAlign: 'center',
    },
    emptySubText: {
      color: 'rgba(255,255,255,0.58)',
      fontSize: font.body,
      fontWeight: '700',
      textAlign: 'center',
      marginTop: spacing.xs,
    },
    emptyActionButton: {
      marginTop: spacing.md,
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      backgroundColor: '#C91D24',
      paddingHorizontal: spacing.lg,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.22)',
    },
    emptyActionText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    cartRow: {
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: '#15151A',
      padding: spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      columnGap: spacing.md,
    },
    cartRowMain: {
      flex: 1,
    },
    cartRowRight: {
      alignItems: 'flex-end',
    },
    cartItemName: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    cartMeta: {
      color: 'rgba(255,255,255,0.60)',
      fontSize: font.small,
      fontWeight: '700',
      marginTop: spacing.xxs,
    },
    cartLineTotal: {
      color: '#FF4C4C',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    quantityControlSmall: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      columnGap: spacing.xs,
      marginTop: spacing.xs,
    },
    quantityButtonSmall: {
      width: control.minTouch - spacing.sm,
      height: control.minTouch - spacing.sm,
      borderRadius: radius.pill,
      backgroundColor: '#C91D24',
      alignItems: 'center',
      justifyContent: 'center',
    },
    quantityButtonText: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    quantityTextSmall: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
      minWidth: spacing.lg,
      textAlign: 'center',
    },
    totalRow: {
      marginTop: spacing.sm,
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(255,80,80,0.30)',
      backgroundColor: 'rgba(201,29,36,0.14)',
      padding: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    totalLabel: {
      color: 'rgba(255,255,255,0.70)',
      fontSize: font.body,
      fontWeight: '800',
    },
    totalValue: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
    },
    billSummaryCard: {
      marginTop: spacing.sm,
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(255,80,80,0.30)',
      backgroundColor: 'rgba(201,29,36,0.13)',
      padding: spacing.md,
      rowGap: spacing.xs,
    },
    billSummaryHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      columnGap: spacing.sm,
      marginBottom: spacing.xs,
    },
    billSummaryTitleWrap: {
      flex: 1,
    },
    billSummaryLabel: {
      color: 'rgba(255,255,255,0.60)',
      fontSize: font.small,
      fontWeight: '900',
      letterSpacing: 0.6,
    },
    billSummaryTitle: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
      marginTop: spacing.xxs,
    },
    billStatusPill: {
      borderRadius: radius.pill,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.18)',
      backgroundColor: 'rgba(0,0,0,0.24)',
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xxs,
    },
    billStatusText: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
    },
    billTotalRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      columnGap: spacing.sm,
    },
    billTotalLabel: {
      color: 'rgba(255,255,255,0.68)',
      fontSize: font.body,
      fontWeight: '800',
    },
    billTotalValue: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    billGrandTotalRow: {
      marginTop: spacing.xs,
      paddingTop: spacing.sm,
      borderTopWidth: border.thin,
      borderTopColor: 'rgba(255,255,255,0.12)',
    },
    billGrandTotalLabel: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    billGrandTotalValue: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
    },
    infoSection: {
      marginTop: spacing.sm,
      rowGap: spacing.sm,
    },
    cartScopeCard: {
      width: '100%',
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.12)',
      backgroundColor: 'rgba(255,255,255,0.055)',
      padding: spacing.sm,
    },
    cartScopeLabel: {
      color: 'rgba(255,255,255,0.52)',
      fontSize: font.small,
      fontWeight: '900',
      letterSpacing: 0.6,
    },
    cartScopeTitle: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
      marginTop: spacing.xxs,
    },
    cartScopeSubTitle: {
      color: 'rgba(255,255,255,0.66)',
      fontSize: font.small,
      fontWeight: '800',
      marginTop: spacing.xxs,
    },
    tablePickerSection: {
      width: '100%',
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(255,255,255,0.04)',
      padding: spacing.sm,
    },
    tablePickerTitle: {
      color: 'rgba(255,255,255,0.68)',
      fontSize: font.small,
      fontWeight: '900',
      marginBottom: spacing.xs,
    },
    tablePickerHint: {
      color: 'rgba(255,255,255,0.56)',
      fontSize: font.small,
      fontWeight: '800',
      marginLeft: spacing.xs,
    },
    tableChipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      columnGap: spacing.xs,
      rowGap: spacing.xs,
      paddingRight: spacing.md,
    },
    tableChip: {
      minWidth: 86,
      minHeight: control.minTouch - spacing.xs,
      borderRadius: radius.pill,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.16)',
      backgroundColor: '#15151A',
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tableChipActive: {
      borderColor: '#FF4C4C',
      backgroundColor: 'rgba(201,29,36,0.24)',
    },
    tableChipDisabled: {
      opacity: 0.35,
    },
    tableChipText: {
      color: 'rgba(255,255,255,0.78)',
      fontSize: font.body,
      fontWeight: '900',
    },
    tableChipTextActive: {
      color: '#FFFFFF',
    },
    lockedTableCard: {
      width: '100%',
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(0,201,94,0.30)',
      backgroundColor: 'rgba(0,201,94,0.11)',
      padding: spacing.sm,
    },
    lockedTableLabel: {
      color: 'rgba(216,255,245,0.72)',
      fontSize: font.small,
      fontWeight: '900',
      letterSpacing: 0.6,
    },
    lockedTableNumber: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
      marginTop: spacing.xxs,
    },
    lockedTableHint: {
      color: 'rgba(216,255,245,0.72)',
      fontSize: font.small,
      fontWeight: '800',
      lineHeight: font.small * 1.42,
      marginTop: spacing.xs,
    },
    inputWrap: {
      width: '100%',
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.11)',
      backgroundColor: '#15151A',
      paddingHorizontal: spacing.sm,
      paddingTop: spacing.xs,
      paddingBottom: spacing.xs,
      alignItems: 'stretch',
    },
    cartDisplayField: {
      minHeight: control.fieldHeight + spacing.md,
      justifyContent: 'center',
    },
    cartDisplayFieldMultiline: {
      minHeight: control.fieldHeight + spacing.lg,
    },
    cartDisplayValue: {
      width: '100%',
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
      marginTop: spacing.xxs,
    },
    cartDisplayValueMultiline: {
      fontSize: font.body,
      lineHeight: font.body * 1.35,
    },
    cartDisplayPlaceholder: {
      color: 'rgba(255,255,255,0.42)',
      fontWeight: '800',
    },
    inputWrapError: {
      borderColor: '#FF4C4C',
      backgroundColor: 'rgba(255,40,40,0.12)',
    },
    inputLabel: {
      color: 'rgba(255,255,255,0.58)',
      fontSize: font.small,
      fontWeight: '900',
      letterSpacing: 0.5,
    },
    input: {
      minHeight: control.fieldHeight,
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '800',
      paddingVertical: 0,
      width: '100%',
    },
    textArea: {
      minHeight: control.fieldHeight + spacing.lg,
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '800',
      textAlignVertical: 'top',
      paddingTop: spacing.xs,
      paddingBottom: spacing.sm,
      width: '100%',
    },
    fieldErrorText: {
      color: '#FF6868',
      fontSize: font.small,
      fontWeight: '900',
      marginTop: spacing.xxs,
      marginLeft: spacing.xs,
    },
    footer: {
      width: '100%',
      borderTopWidth: border.thin,
      borderTopColor: 'rgba(255,255,255,0.10)',
      backgroundColor: '#101014',
      paddingHorizontal: spacing.md,
      paddingTop: spacing.sm,
      paddingBottom: spacing.md,
    },
    primaryButton: {
      width: '100%',
      minHeight: control.buttonHeight,
      borderRadius: radius.pill,
      backgroundColor: '#C91D24',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.md,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.22)',
    },
    primaryButtonText: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    loadingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      columnGap: spacing.sm,
    },
    disabledButton: {
      opacity: 0.45,
    },
  });
};

export default createStyles;
