import {StyleSheet} from 'react-native';

import type {DesignSystem} from 'theme/designSystem';

type Args = {
  design: DesignSystem;
  isWide: boolean;
};

const createStyles = ({design, isWide}: Args) => {
  const {spacing, radius, font, safeArea, control} = design;

  return StyleSheet.create({
    screen: {
      flex: 1,
      alignItems: 'stretch',
      backgroundColor: '#050506',
      paddingTop: safeArea.top + spacing.sm,
      paddingBottom: safeArea.bottom + spacing.sm,
      paddingHorizontal: spacing.md,
    },
    glowTop: {
      position: 'absolute',
      zIndex: 0,
      top: -140,
      right: -120,
      width: 320,
      height: 320,
      borderRadius: 160,
      backgroundColor: 'rgba(201,29,36,0.16)',
    },
    glowBottom: {
      position: 'absolute',
      zIndex: 0,
      bottom: -180,
      left: -140,
      width: 360,
      height: 360,
      borderRadius: 180,
      backgroundColor: 'rgba(255,255,255,0.035)',
    },
    authGuardCard: {
      alignSelf: 'center',
      width: '100%',
      maxWidth: 520,
      marginTop: safeArea.top + spacing.xl,
      padding: spacing.lg,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(14,14,18,0.96)',
      alignItems: 'center',
      gap: spacing.sm,
    },
    authGuardTitle: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
      textAlign: 'center',
    },
    authGuardHint: {
      color: 'rgba(255,255,255,0.58)',
      fontSize: font.body,
      lineHeight: font.body * 1.45,
      textAlign: 'center',
    },
    header: {
      width: '100%',
      zIndex: 2,
      alignSelf: 'stretch',
      minHeight: isWide ? control.headerHeight : 0,
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.md,
      paddingVertical: isWide ? spacing.sm : spacing.xs,
      borderRadius: radius.xl,
      backgroundColor: 'rgba(14,14,18,0.94)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      marginBottom: spacing.md,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flexGrow: 1,
      flexShrink: 1,
      flexBasis: isWide ? 0 : '100%',
      minWidth: 0,
      marginBottom: isWide ? 0 : spacing.xs,
    },
    logo: {
      width: isWide ? 54 : 42,
      height: isWide ? 54 : 42,
      marginRight: spacing.sm,
    },
    eyebrow: {
      color: '#E53A42',
      fontSize: font.small,
      fontWeight: '800',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    headerTitle: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
    },
    headerMeta: {
      color: 'rgba(255,255,255,0.56)',
      fontSize: font.small,
      marginTop: 2,
    },
    logoutButton: {
      minHeight: control.minTouch,
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(229,58,66,0.42)',
      backgroundColor: 'rgba(201,29,36,0.14)',
      marginLeft: isWide ? spacing.sm : 0,
      marginTop: isWide ? 0 : spacing.xs,
      flexGrow: isWide ? 0 : 1,
    },
    logoutText: {
      color: '#FFFFFF',
      fontWeight: '800',
      fontSize: font.body,
      textAlign: 'center',
    },
    headerActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: isWide ? 'flex-end' : 'space-between',
      gap: spacing.xs,
      flexGrow: isWide ? 0 : 1,
      flexBasis: isWide ? undefined : '100%',
    },
    backToAdminButton: {
      minHeight: control.minTouch,
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.18)',
      backgroundColor: 'rgba(255,255,255,0.07)',
      flexGrow: isWide ? 0 : 1,
    },
    backToAdminText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
      textAlign: 'center',
    },
    inlineErrorBox: {
      width: '100%',
      alignSelf: 'stretch',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(255,92,92,0.32)',
      backgroundColor: 'rgba(201,29,36,0.14)',
      marginBottom: spacing.sm,
    },
    inlineErrorText: {
      color: '#FFD9D9',
      fontSize: font.body,
      fontWeight: '700',
    },
    homeScroll: {
      flex: 1,
      width: '100%',
      alignSelf: 'stretch',
    },
    homeScrollBody: {
      flexGrow: 1,
      paddingBottom: spacing.xl,
    },
    homeIntroCard: {
      width: '100%',
      alignSelf: 'stretch',
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(14,14,18,0.92)',
      padding: spacing.md,
      marginBottom: spacing.sm,
    },
    homeIntroEyebrow: {
      color: '#E53A42',
      fontSize: font.small,
      fontWeight: '900',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    homeIntroTitle: {
      color: '#FFFFFF',
      fontSize: font.title,
      lineHeight: font.title * 1.2,
      fontWeight: '900',
      marginTop: spacing.xs,
    },
    homeIntroHint: {
      color: 'rgba(255,255,255,0.58)',
      fontSize: font.body,
      lineHeight: font.body * 1.42,
      marginTop: spacing.xs,
      fontWeight: '700',
    },
    adminPageGrid: {
      width: '100%',
      alignSelf: 'stretch',
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    adminPageCard: {
      minHeight: isWide ? 132 : 116,
      width: '100%',
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(18,18,22,0.96)',
      padding: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    adminPageIcon: {
      width: 44,
      height: 44,
      borderRadius: 22,
      overflow: 'hidden',
      color: '#FFFFFF',
      backgroundColor: '#C91D24',
      textAlign: 'center',
      textAlignVertical: 'center',
      fontSize: font.title,
      fontWeight: '900',
    },
    adminPageContent: {
      flex: 1,
      minWidth: 0,
    },
    adminPageTitle: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      lineHeight: font.bodyLarge * 1.22,
      fontWeight: '900',
    },
    adminPageHint: {
      color: 'rgba(255,255,255,0.56)',
      fontSize: font.small,
      lineHeight: font.small * 1.35,
      fontWeight: '700',
      marginTop: 3,
    },
    adminPageMeta: {
      color: '#FFE3AE',
      fontSize: font.small,
      lineHeight: font.small * 1.3,
      fontWeight: '900',
      marginTop: spacing.xs,
    },
    adminPageArrow: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
      minWidth: 54,
      textAlign: 'right',
    },
    pageContextBar: {
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(229,58,66,0.30)',
      backgroundColor: 'rgba(201,29,36,0.13)',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      marginBottom: spacing.md,
    },
    pageContextText: {
      color: '#FFFFFF',
      fontSize: font.small,
      lineHeight: font.small * 1.35,
      fontWeight: '900',
      textAlign: 'center',
    },
    workspacePanel: {
      width: '100%',
      alignSelf: 'stretch',
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(14,14,18,0.88)',
      paddingHorizontal: spacing.md,
      paddingVertical: isWide ? spacing.sm : spacing.xs,
      marginBottom: spacing.sm,
      gap: spacing.xs,
    },
    workspaceHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
      flexWrap: 'wrap',
    },
    workspaceTitleBlock: {
      flex: 1,
      minWidth: 220,
    },
    workspaceEyebrow: {
      color: '#E53A42',
      fontSize: font.small,
      fontWeight: '900',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    workspaceTitle: {
      color: '#FFFFFF',
      fontSize: isWide ? font.bodyLarge : font.body,
      lineHeight: (isWide ? font.bodyLarge : font.body) * 1.2,
      fontWeight: '900',
      marginTop: 2,
    },
    workspaceHint: {
      color: 'rgba(255,255,255,0.56)',
      fontSize: font.small,
      lineHeight: font.small * 1.35,
      fontWeight: '700',
      marginTop: 2,
    },
    workspaceStatusPill: {
      alignSelf: 'flex-start',
      marginTop: spacing.xs,
      color: '#FFFFFF',
      fontSize: font.small,
      lineHeight: font.small * 1.25,
      fontWeight: '900',
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(229,58,66,0.42)',
      backgroundColor: 'rgba(201,29,36,0.16)',
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs,
      overflow: 'hidden',
    },
    workspaceWarningBox: {
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(255,192,88,0.32)',
      backgroundColor: 'rgba(255,192,88,0.08)',
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs,
    },
    workspaceWarningText: {
      color: '#FFE3AE',
      fontSize: font.small,
      fontWeight: '800',
    },
    workspaceControlsGrid: {
      flexDirection: isWide ? 'row' : 'column',
      gap: spacing.sm,
      width: '100%',
      alignSelf: 'stretch',
    },
    workspaceSection: {
      flex: 1,
      minWidth: isWide ? 240 : undefined,
      gap: spacing.xs,
      marginTop: spacing.xs,
    },
    workspaceSectionLabel: {
      marginBottom: spacing.xs,
      color: 'rgba(255,255,255,0.56)',
      fontSize: font.small,
      lineHeight: font.small * 1.25,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    workspaceChipRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
      paddingRight: spacing.md,
    },
    workspaceChip: {
      minHeight: isWide ? 38 : control.minTouch,
      marginRight: spacing.xs,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.11)',
      backgroundColor: 'rgba(255,255,255,0.055)',
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    workspaceChipActive: {
      borderColor: 'rgba(229,58,66,0.58)',
      backgroundColor: 'rgba(201,29,36,0.22)',
    },
    workspaceChipDisabled: {
      opacity: 0.62,
    },
    workspaceChipText: {
      color: 'rgba(255,255,255,0.72)',
      fontSize: font.body,
      fontWeight: '800',
    },
    workspaceChipTextActive: {
      color: '#FFFFFF',
      fontWeight: '900',
    },
    workspaceEmptyText: {
      color: 'rgba(255,255,255,0.5)',
      fontSize: font.body,
      fontWeight: '700',
      paddingVertical: spacing.xs,
    },
    body: {
      flex: 1,
      zIndex: 4,
      width: '100%',
      alignSelf: 'stretch',
      flexDirection: 'column',
      gap: spacing.sm,
      minHeight: 0,
    },
    mainColumn: {
      flex: 1,
      minWidth: 0,
      minHeight: 0,
      alignSelf: 'stretch',
    },
    navigationPanel: {
      width: '100%',
      alignSelf: 'stretch',
      zIndex: 8,
      elevation: 8,
      gap: spacing.xs,
    },
    sidebar: {
      width: '100%',
      alignSelf: 'stretch',
      flexShrink: 0,
      zIndex: 9,
      elevation: 9,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(12,12,15,0.96)',
      padding: spacing.xs,
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: spacing.xs,
    },
    sidebarHeader: {
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs,
      minWidth: isWide ? 170 : '100%',
      flexGrow: isWide ? 0 : 0,
      flexShrink: 0,
    },
    sidebarTitle: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    sidebarHint: {
      color: 'rgba(255,255,255,0.48)',
      fontSize: font.small,
      marginTop: 2,
    },
    sidebarItem: {
      minHeight: control.buttonHeight,
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.06)',
      backgroundColor: 'rgba(255,255,255,0.04)',
      paddingHorizontal: spacing.sm,
      flexGrow: 1,
      flexShrink: 1,
      flexBasis: isWide ? 190 : '47%',
      minWidth: 150,
      overflow: 'hidden',
    },
    sidebarItemActive: {
      borderColor: 'rgba(229,58,66,0.46)',
      backgroundColor: 'rgba(201,29,36,0.18)',
    },
    sidebarItemPressed: {
      opacity: 0.78,
      transform: [{scale: 0.99}],
    },
    sidebarIcon: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: 'rgba(255,255,255,0.08)',
      color: '#FFFFFF',
      textAlign: 'center',
      textAlignVertical: 'center',
      fontWeight: '900',
      marginRight: spacing.sm,
    },
    sidebarIconActive: {
      backgroundColor: '#C91D24',
    },
    sidebarTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    sidebarLabel: {
      color: 'rgba(255,255,255,0.78)',
      fontSize: font.body,
      fontWeight: '800',
      flexShrink: 1,
    },
    sidebarLabelActive: {
      color: '#FFFFFF',
    },
    sidebarItemHint: {
      color: 'rgba(255,255,255,0.42)',
      fontSize: font.small,
      marginTop: 2,
    },
    activeTabNotice: {
      alignSelf: 'stretch',
      zIndex: 9,
      elevation: 9,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(229,58,66,0.34)',
      backgroundColor: 'rgba(201,29,36,0.14)',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.xs,
    },
    activeTabNoticeText: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
      textAlign: 'center',
    },
    contentPanel: {
      flex: 1,
      zIndex: 6,
      elevation: 6,
      alignSelf: 'stretch',
      minWidth: 0,
      minHeight: 0,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(9,9,12,0.92)',
      overflow: 'hidden',
    },
    contentScroll: {
      flex: 1,
    },
    contentScrollBody: {
      flexGrow: 1,
      padding: spacing.md,
      paddingTop: spacing.sm,
      paddingBottom: spacing.xl,
    },
    workspaceFooter: {
      marginTop: spacing.md,
    },
    kpiRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginBottom: spacing.md,
    },
    kpiCard: {
      minWidth: isWide ? 150 : '47%',
      flexGrow: 1,
      padding: spacing.md,
      borderRadius: radius.lg,
      backgroundColor: 'rgba(255,255,255,0.055)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    kpiValue: {
      color: '#FFFFFF',
      fontSize: font.titleLarge,
      fontWeight: '900',
    },
    kpiLabel: {
      color: 'rgba(255,255,255,0.54)',
      fontSize: font.small,
      marginTop: 4,
    },
    orderFlowBoard: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
      marginBottom: spacing.sm,
      padding: spacing.xs,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.035)',
    },
    orderFlowStage: {
      minHeight: control.minTouch,
      minWidth: isWide ? 116 : '30%',
      flexGrow: 1,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.045)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    orderFlowStageActive: {
      borderColor: 'rgba(229,58,66,0.56)',
      backgroundColor: 'rgba(201,29,36,0.22)',
    },
    orderFlowStageCount: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
    },
    orderFlowStageLabel: {
      color: 'rgba(255,255,255,0.64)',
      fontSize: font.small,
      fontWeight: '800',
      marginTop: 2,
      textAlign: 'center',
    },
    paymentSummaryRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
      marginBottom: spacing.md,
    },
    paymentSummaryText: {
      color: 'rgba(255,255,255,0.64)',
      fontSize: font.small,
      fontWeight: '800',
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs,
      borderRadius: radius.pill,
      backgroundColor: 'rgba(255,255,255,0.055)',
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: spacing.sm,
      marginBottom: spacing.md,
      flexWrap: 'wrap',
    },
    sectionTitleBlock: {
      flex: 1,
      minWidth: isWide ? 360 : 220,
    },
    sectionTitle: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
    },
    sectionHint: {
      color: 'rgba(255,255,255,0.52)',
      fontSize: font.body,
      marginTop: 4,
      maxWidth: 720,
    },
    orderSyncPanel: {
      alignItems: isWide ? 'flex-end' : 'stretch',
      alignSelf: isWide ? 'flex-start' : 'stretch',
      minWidth: isWide ? 230 : '100%',
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.04)',
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs,
    },
    orderSyncStatus: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
      textAlign: isWide ? 'right' : 'left',
    },
    orderSyncTime: {
      color: 'rgba(255,255,255,0.52)',
      fontSize: font.small,
      fontWeight: '700',
      marginTop: 2,
      textAlign: isWide ? 'right' : 'left',
    },
    orderSyncNotice: {
      color: '#FFE3AE',
      fontSize: font.small,
      fontWeight: '900',
      marginBottom: spacing.xs,
      textAlign: isWide ? 'right' : 'left',
    },
    orderRefreshButton: {
      minHeight: control.minTouch,
      marginTop: spacing.xs,
      paddingHorizontal: spacing.sm,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(229,58,66,0.42)',
      backgroundColor: 'rgba(201,29,36,0.16)',
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: isWide ? 'flex-end' : 'stretch',
    },
    orderRefreshButtonText: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
      textAlign: 'center',
    },
    filterWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
      marginBottom: spacing.md,
    },
    filterChip: {
      minHeight: control.minTouch,
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.04)',
    },
    filterChipActive: {
      borderColor: 'rgba(229,58,66,0.5)',
      backgroundColor: 'rgba(201,29,36,0.22)',
    },
    filterText: {
      color: 'rgba(255,255,255,0.68)',
      fontWeight: '800',
      fontSize: font.body,
    },
    filterTextActive: {
      color: '#FFFFFF',
    },
    orderGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.md,
    },
    billSessionGrid: {
      gap: spacing.lg,
    },
    billSessionCard: {
      width: '100%',
      borderRadius: radius.xxl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.11)',
      backgroundColor: 'rgba(13,13,18,0.98)',
      padding: spacing.md,
    },
    billSessionHeader: {
      flexDirection: isWide ? 'row' : 'column',
      justifyContent: 'space-between',
      alignItems: isWide ? 'flex-start' : 'stretch',
      gap: spacing.sm,
    },
    billSessionTitleBlock: {
      flex: 1,
      minWidth: 0,
    },
    billSessionCode: {
      color: 'rgba(255,255,255,0.46)',
      fontSize: font.small,
      fontWeight: '800',
    },
    billSessionTable: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
      marginTop: spacing.xxs,
    },
    billSessionMeta: {
      color: 'rgba(255,255,255,0.52)',
      fontSize: font.small,
      fontWeight: '700',
      marginTop: spacing.xxs,
    },
    billSessionStatusPill: {
      minHeight: 34,
      paddingHorizontal: spacing.md,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(60,210,150,0.32)',
      backgroundColor: 'rgba(9,168,107,0.16)',
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: isWide ? 'flex-start' : 'flex-start',
    },
    billSessionStatusText: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
    },
    billSessionSummaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginTop: spacing.md,
    },
    billSessionSummaryItem: {
      flexGrow: 1,
      flexBasis: isWide ? '30%' : '100%',
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.045)',
      padding: spacing.sm,
    },
    billSessionSummaryValue: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    billSessionSummaryLabel: {
      color: 'rgba(255,255,255,0.52)',
      fontSize: font.small,
      fontWeight: '800',
      marginTop: 2,
    },
    billPaymentSummaryBox: {
      marginTop: spacing.md,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.035)',
      padding: spacing.sm,
      gap: spacing.xs,
    },
    billPaymentSummaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: spacing.sm,
      alignItems: 'center',
    },
    billPaymentSummaryLabel: {
      color: 'rgba(255,255,255,0.56)',
      fontSize: font.small,
      fontWeight: '800',
      flex: 1,
    },
    billPaymentSummaryValue: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
      flexShrink: 1,
      textAlign: 'right',
    },
    billPaymentActionBlock: {
      marginTop: spacing.md,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(60,210,150,0.20)',
      backgroundColor: 'rgba(9,168,107,0.08)',
      padding: spacing.sm,
      gap: spacing.sm,
    },
    billPaymentActionHeader: {
      gap: spacing.xxs,
    },
    billPaymentActionTitle: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    billPaymentActionHint: {
      color: 'rgba(255,255,255,0.58)',
      fontSize: font.small,
      fontWeight: '700',
      lineHeight: font.small * 1.35,
    },
    billPaymentActionRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
    },
    billPaymentSecondaryButton: {
      minHeight: control.minTouch,
      paddingHorizontal: spacing.md,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,227,174,0.42)',
      backgroundColor: 'rgba(255,227,174,0.10)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    billPaymentSecondaryButtonText: {
      color: '#FFE3AE',
      fontSize: font.body,
      fontWeight: '900',
      textAlign: 'center',
    },
    billPaymentPrimaryButton: {
      minHeight: control.minTouch,
      maxWidth: isWide ? 240 : '100%',
      paddingHorizontal: spacing.md,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(60,210,150,0.42)',
      backgroundColor: 'rgba(9,168,107,0.18)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    billPaymentPrimaryButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
      textAlign: 'center',
    },
    billPaymentCloseButton: {
      minHeight: control.minTouch,
      paddingHorizontal: spacing.md,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(229,58,66,0.46)',
      backgroundColor: 'rgba(201,29,36,0.18)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    billPaymentCloseButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
      textAlign: 'center',
    },
    billTransferBlock: {
      marginTop: spacing.md,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.035)',
      padding: spacing.sm,
      gap: spacing.sm,
    },
    billTransferButton: {
      minHeight: control.minTouch,
      alignSelf: isWide ? 'flex-start' : 'stretch',
      paddingHorizontal: spacing.md,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,227,174,0.42)',
      backgroundColor: 'rgba(255,227,174,0.10)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    billTransferButtonText: {
      color: '#FFE3AE',
      fontSize: font.body,
      fontWeight: '900',
      textAlign: 'center',
    },
    billTransferPanel: {
      gap: spacing.sm,
    },
    billTransferHint: {
      color: 'rgba(255,255,255,0.58)',
      fontSize: font.small,
      fontWeight: '700',
      lineHeight: font.small * 1.35,
    },
    billTransferChipWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
    },
    billTransferChip: {
      minHeight: control.minTouch,
      maxWidth: isWide ? 180 : '100%',
      paddingHorizontal: spacing.md,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
      backgroundColor: 'rgba(255,255,255,0.06)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    billTransferChipText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    billTransferEmpty: {
      color: 'rgba(255,255,255,0.52)',
      fontSize: font.small,
      fontWeight: '800',
    },
    billSessionChildHeader: {
      borderTopWidth: 1,
      borderTopColor: 'rgba(255,255,255,0.08)',
      marginTop: spacing.md,
      paddingTop: spacing.md,
    },
    billSessionChildTitle: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
    },
    billSessionChildHint: {
      color: 'rgba(255,255,255,0.52)',
      fontSize: font.small,
      fontWeight: '700',
      marginTop: spacing.xxs,
    },
    billSessionChildGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.md,
      marginTop: spacing.md,
    },
    orderCard: {
      width: isWide ? '48.5%' : '100%',
      minWidth: isWide ? 360 : undefined,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.09)',
      backgroundColor: 'rgba(18,18,22,0.98)',
      padding: spacing.md,
    },
    orderHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: spacing.sm,
    },
    orderTitleBlock: {
      flex: 1,
      minWidth: 0,
    },
    orderCode: {
      color: 'rgba(255,255,255,0.48)',
      fontSize: font.small,
      fontWeight: '700',
    },
    orderTable: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
      marginTop: 2,
    },
    orderTime: {
      color: 'rgba(255,255,255,0.5)',
      fontSize: font.small,
      marginTop: 3,
    },
    orderMetaLine: {
      color: 'rgba(255,255,255,0.42)',
      fontSize: font.small,
      fontWeight: '700',
      marginTop: 3,
    },
    orderBadgeColumn: {
      alignItems: 'flex-end',
      gap: spacing.xs,
    },
    badge: {
      borderWidth: 1,
      borderRadius: radius.pill,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xxs,
    },
    badgeText: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
    },
    orderNote: {
      color: 'rgba(255,255,255,0.68)',
      fontSize: font.body,
      marginTop: spacing.sm,
      padding: spacing.sm,
      borderRadius: radius.md,
      backgroundColor: 'rgba(255,255,255,0.04)',
    },
    orderItems: {
      marginTop: spacing.sm,
      gap: spacing.xs,
    },
    orderItemRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: spacing.sm,
    },
    orderItemName: {
      color: '#FFFFFF',
      fontSize: font.body,
      flex: 1,
      minWidth: 0,
    },
    orderItemPrice: {
      color: 'rgba(255,255,255,0.64)',
      fontSize: font.body,
      fontWeight: '800',
    },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderTopWidth: 1,
      borderTopColor: 'rgba(255,255,255,0.08)',
      marginTop: spacing.sm,
      paddingTop: spacing.sm,
    },
    totalLabel: {
      color: 'rgba(255,255,255,0.55)',
      fontSize: font.body,
    },
    totalValue: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    primaryOrderActionButton: {
      minHeight: control.buttonHeight,
      marginTop: spacing.md,
      borderRadius: radius.pill,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#C91D24',
      paddingHorizontal: spacing.md,
    },
    primaryOrderActionText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
      textAlign: 'center',
    },
    orderTerminalNotice: {
      marginTop: spacing.md,
      padding: spacing.sm,
      borderRadius: radius.lg,
      backgroundColor: 'rgba(255,255,255,0.045)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    orderTerminalNoticeText: {
      color: 'rgba(255,255,255,0.62)',
      fontSize: font.small,
      fontWeight: '800',
      textAlign: 'center',
    },
    actionLabel: {
      color: 'rgba(255,255,255,0.55)',
      fontSize: font.small,
      fontWeight: '800',
      marginTop: spacing.sm,
      marginBottom: spacing.xs,
    },
    actionChipWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
    },
    actionChip: {
      minHeight: 34,
      paddingHorizontal: spacing.sm,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.04)',
    },
    actionChipActive: {
      borderColor: 'rgba(229,58,66,0.5)',
      backgroundColor: 'rgba(201,29,36,0.22)',
    },
    paymentChipActive: {
      borderColor: 'rgba(60,210,150,0.38)',
      backgroundColor: 'rgba(9,168,107,0.20)',
    },
    paymentMethodChipActive: {
      borderColor: 'rgba(242,165,26,0.45)',
      backgroundColor: 'rgba(242,165,26,0.18)',
    },
    actionChipDisabled: {
      opacity: 0.38,
    },
    actionChipText: {
      color: 'rgba(255,255,255,0.65)',
      fontSize: font.small,
      fontWeight: '800',
    },
    actionChipTextActive: {
      color: '#FFFFFF',
    },
    actionChipTextDisabled: {
      color: 'rgba(255,255,255,0.38)',
    },
    sectionHeaderActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      alignItems: 'center',
      gap: spacing.xs,
    },
    headerSecondaryButton: {
      minHeight: control.buttonHeight,
      paddingHorizontal: spacing.md,
      borderRadius: radius.pill,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
      backgroundColor: 'rgba(255,255,255,0.06)',
    },
    headerSecondaryButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
      textAlign: 'center',
    },
    primaryButton: {
      minHeight: control.buttonHeight,
      paddingHorizontal: spacing.md,
      borderRadius: radius.pill,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#C91D24',
    },
    primaryButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
      textAlign: 'center',
    },
    grid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.md,
    },
    adminFilterPanel: {
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.035)',
      padding: spacing.md,
      marginBottom: spacing.md,
    },
    adminStatusSummaryRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginBottom: spacing.md,
    },
    adminStatusSummaryCard: {
      flexGrow: 1,
      minWidth: isWide ? 130 : '31%',
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.045)',
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.sm,
    },
    adminStatusSummaryValue: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
    },
    adminStatusSummaryLabel: {
      color: 'rgba(255,255,255,0.55)',
      fontSize: font.small,
      fontWeight: '800',
      marginTop: 2,
    },
    adminSearchRow: {
      flexDirection: isWide ? 'row' : 'column',
      alignItems: isWide ? 'flex-end' : 'stretch',
      gap: spacing.sm,
    },
    adminSearchBox: {
      flex: 1,
      minWidth: isWide ? 320 : undefined,
    },
    adminFilterSummaryRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
      marginTop: spacing.md,
      paddingTop: spacing.sm,
      borderTopWidth: 1,
      borderTopColor: 'rgba(255,255,255,0.08)',
    },
    adminFilterSummaryText: {
      color: 'rgba(255,255,255,0.62)',
      fontSize: font.body,
      fontWeight: '800',
    },
    menuCard: {
      width: isWide ? '31.8%' : '100%',
      minWidth: isWide ? 260 : undefined,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.09)',
      backgroundColor: 'rgba(18,18,22,0.98)',
      overflow: 'hidden',
    },
    menuThumb: {
      width: '100%',
      height: isWide ? 130 : 150,
      backgroundColor: 'rgba(255,255,255,0.07)',
    },
    menuInfo: {
      padding: spacing.md,
    },
    menuName: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    menuMeta: {
      color: 'rgba(255,255,255,0.52)',
      fontSize: font.small,
      marginTop: 4,
    },
    priceText: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
      marginTop: spacing.xs,
    },
    statusPill: {
      alignSelf: 'flex-start',
      borderWidth: 1,
      borderRadius: radius.pill,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xxs,
      marginTop: spacing.xs,
    },
    statusPillText: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
    },
    secondaryButton: {
      minHeight: control.minTouch,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(229,58,66,0.38)',
      marginTop: spacing.sm,
    },
    secondaryButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
      textAlign: 'center',
    },
    menuCardActionRow: {
      flexDirection: 'row',
      gap: spacing.xs,
      marginTop: spacing.sm,
    },
    menuCardActionButton: {
      flex: 1,
      marginTop: 0,
      paddingHorizontal: spacing.sm,
    },

    branchQrPanel: {
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(229,58,66,0.24)',
      backgroundColor: 'rgba(229,58,66,0.07)',
      padding: spacing.md,
      marginBottom: spacing.md,
    },
    branchQrHeaderRow: {
      flexDirection: isWide ? 'row' : 'column',
      alignItems: isWide ? 'flex-start' : 'stretch',
      justifyContent: 'space-between',
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    branchQrEyebrow: {
      color: 'rgba(255,255,255,0.55)',
      fontSize: font.small,
      fontWeight: '900',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      marginBottom: spacing.xxs,
    },
    branchQrTitle: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
    },
    branchQrHint: {
      color: 'rgba(255,255,255,0.68)',
      fontSize: font.body,
      lineHeight: font.body + 5,
      marginTop: spacing.xxs,
    },
    branchQrStatusPill: {
      alignSelf: isWide ? 'flex-start' : 'stretch',
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.16)',
      backgroundColor: 'rgba(255,255,255,0.08)',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.xs,
    },
    branchQrStatusText: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
      textAlign: 'center',
    },
    branchQrColumns: {
      flexDirection: isWide ? 'row' : 'column',
      gap: spacing.md,
      marginTop: spacing.sm,
    },
    branchQrPreviewCard: {
      width: isWide ? 230 : '100%',
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.1)',
      backgroundColor: 'rgba(0,0,0,0.2)',
      padding: spacing.md,
      alignItems: 'center',
    },
    branchQrFormCard: {
      flex: 1,
      minWidth: isWide ? 320 : undefined,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(0,0,0,0.12)',
      padding: spacing.md,
    },
    branchQrPreviewTitle: {
      color: 'rgba(255,255,255,0.74)',
      fontSize: font.body,
      fontWeight: '900',
      marginBottom: spacing.sm,
      textAlign: 'center',
    },
    branchQrCodeBox: {
      width: 166,
      height: 166,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.lg,
      backgroundColor: '#FFFFFF',
      marginBottom: spacing.sm,
    },
    branchQrPrintUrl: {
      color: 'rgba(255,255,255,0.55)',
      fontSize: font.small,
      fontWeight: '700',
      textAlign: 'center',
      marginTop: spacing.xs,
    },
    branchQrStatusHint: {
      color: 'rgba(255,255,255,0.62)',
      fontSize: font.small,
      fontWeight: '700',
      marginTop: spacing.xs,
    },
    branchQrActions: {
      alignItems: 'flex-start',
      marginTop: spacing.md,
    },
    tableManagerPanel: {
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.035)',
      padding: spacing.md,
      marginBottom: spacing.md,
    },
    tableFormGrid: {
      flexDirection: isWide ? 'row' : 'column',
      gap: spacing.sm,
    },
    tableFormColumn: {
      flex: 1,
      minWidth: isWide ? 260 : undefined,
    },
    tableGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.md,
    },
    tableCard: {
      width: isWide ? '48.5%' : '100%',
      minWidth: isWide ? 340 : undefined,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.09)',
      backgroundColor: 'rgba(18,18,22,0.98)',
      padding: spacing.md,
    },
    qrTokenBox: {
      marginTop: spacing.sm,
      padding: spacing.sm,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.045)',
    },
    qrTokenLabel: {
      color: 'rgba(255,255,255,0.48)',
      fontSize: font.small,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    qrTokenValue: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '800',
      marginTop: 4,
    },
    qrCopyTextInput: {
      backgroundColor: 'rgba(0,0,0,0.18)',
      borderRadius: radius.sm,
      color: '#FFFFFF',
      marginTop: spacing.xs,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs,
      textAlignVertical: 'top',
    },
    qrCopyActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
      marginTop: spacing.sm,
    },
    qrCopyButton: {
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.18)',
      backgroundColor: 'rgba(255,255,255,0.08)',
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs,
    },
    qrCopyButtonText: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
    },
    tableCardActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
      marginTop: spacing.sm,
    },
    tableActionButton: {
      flex: 1,
      minWidth: 120,
    },
    disabledButton: {
      opacity: 0.62,
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: spacing.xxl,
      paddingHorizontal: spacing.md,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.035)',
    },
    emptyIcon: {
      fontSize: 38,
      marginBottom: spacing.xs,
    },
    emptyText: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
      textAlign: 'center',
    },
    emptySubText: {
      color: 'rgba(255,255,255,0.52)',
      fontSize: font.body,
      textAlign: 'center',
      marginTop: spacing.xs,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.72)',
      alignItems: 'center',
      justifyContent: 'center',
      padding: spacing.md,
    },
    editModalCard: {
      width: '100%',
      maxWidth: 720,
      maxHeight: '92%',
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
      backgroundColor: '#111116',
      padding: spacing.md,
    },
    editModalHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: spacing.md,
      gap: spacing.sm,
    },
    editModalTitle: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
    },
    editModalHint: {
      color: 'rgba(255,255,255,0.48)',
      fontSize: font.small,
      marginTop: 4,
    },
    modalCloseButton: {
      width: control.minTouch,
      height: control.minTouch,
      borderRadius: radius.pill,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.08)',
    },
    modalCloseText: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
    },
    imagePickerCard: {
      flexDirection: isWide ? 'row' : 'column',
      gap: spacing.md,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(255,255,255,0.045)',
      padding: spacing.sm,
    },
    imagePickerPreview: {
      width: isWide ? 170 : '100%',
      height: isWide ? 126 : 168,
      borderRadius: radius.lg,
      backgroundColor: 'rgba(255,255,255,0.07)',
      overflow: 'hidden',
    },
    imagePickerPlaceholder: {
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: 'rgba(255,255,255,0.16)',
    },
    imagePickerPlaceholderText: {
      color: 'rgba(255,255,255,0.46)',
      fontSize: font.body,
      fontWeight: '800',
    },
    imagePickerInfo: {
      flex: 1,
      minWidth: 0,
      justifyContent: 'center',
    },
    imagePickerTitle: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    imagePickerHint: {
      color: 'rgba(255,255,255,0.50)',
      fontSize: font.small,
      marginTop: spacing.xs,
    },
    imagePickerButtonRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
      marginTop: spacing.sm,
    },
    imagePickerButton: {
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      backgroundColor: '#C91D24',
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    imagePickerButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
      textAlign: 'center',
    },
    imageRemoveButton: {
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    imageRemoveButtonText: {
      color: 'rgba(255,255,255,0.82)',
      fontSize: font.body,
      fontWeight: '800',
      textAlign: 'center',
    },
    categoryManagerCard: {
      width: '100%',
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
      backgroundColor: 'rgba(18,18,22,0.98)',
      padding: spacing.md,
    },
    categoryFormRow: {
      flexDirection: isWide ? 'row' : 'column',
      alignItems: isWide ? 'flex-end' : 'stretch',
      gap: spacing.sm,
      marginTop: spacing.md,
    },
    categoryInputColumn: {
      flex: 1,
      minWidth: isWide ? 320 : undefined,
    },
    categoryList: {
      marginTop: spacing.md,
      gap: spacing.sm,
    },
    categoryRow: {
      flexDirection: isWide ? 'row' : 'column',
      alignItems: isWide ? 'center' : 'stretch',
      justifyContent: 'space-between',
      gap: spacing.sm,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.045)',
      padding: spacing.sm,
    },
    categoryRowActive: {
      borderColor: 'rgba(229,58,66,0.46)',
      backgroundColor: 'rgba(201,29,36,0.16)',
    },
    categoryInfo: {
      flex: 1,
      minWidth: 0,
    },
    categoryName: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    categoryMeta: {
      color: 'rgba(255,255,255,0.48)',
      fontSize: font.small,
      marginTop: 3,
      fontWeight: '700',
    },
    categoryActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      gap: spacing.xs,
    },
    dangerButton: {
      minHeight: control.buttonHeight,
      paddingHorizontal: spacing.md,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,105,105,0.42)',
      backgroundColor: 'rgba(255,75,75,0.14)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    dangerButtonText: {
      color: '#FFB3B3',
      fontSize: font.body,
      fontWeight: '900',
      textAlign: 'center',
    },
    inputLabel: {
      color: 'rgba(255,255,255,0.75)',
      fontSize: font.small,
      fontWeight: '900',
      marginBottom: spacing.xs,
      marginTop: spacing.sm,
    },
    adminInput: {
      minHeight: control.fieldHeight,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(255,255,255,0.055)',
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      paddingHorizontal: spacing.md,
    },
    adminInputButton: {
      justifyContent: 'center',
      paddingVertical: spacing.sm,
    },
    adminInputValueText: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '800',
    },
    adminInputPlaceholderText: {
      color: 'rgba(255,255,255,0.36)',
      fontSize: font.bodyLarge,
      fontWeight: '700',
    },
    adminTextArea: {
      minHeight: 96,
      paddingTop: spacing.sm,
      textAlignVertical: 'top',
    },
    categoryPickerWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
    },
    categoryPickChip: {
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(255,255,255,0.05)',
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    categoryPickChipActive: {
      borderColor: 'rgba(229,58,66,0.48)',
      backgroundColor: 'rgba(201,29,36,0.20)',
    },
    categoryPickText: {
      color: 'rgba(255,255,255,0.65)',
      fontSize: font.body,
      fontWeight: '800',
    },
    categoryPickTextActive: {
      color: '#FFFFFF',
    },
    formError: {
      color: '#FF7777',
      fontSize: font.body,
      fontWeight: '800',
      marginTop: spacing.sm,
    },
    editModalFooter: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      gap: spacing.sm,
      borderTopWidth: 1,
      borderTopColor: 'rgba(255,255,255,0.08)',
      marginTop: spacing.md,
      paddingTop: spacing.md,
    },
    cancelButton: {
      minHeight: control.buttonHeight,
      paddingHorizontal: spacing.md,
      flexGrow: isWide ? 0 : 1,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cancelButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '800',
      textAlign: 'center',
    },
    saveButton: {
      minHeight: control.buttonHeight,
      paddingHorizontal: spacing.lg,
      flexGrow: isWide ? 0 : 1,
      borderRadius: radius.pill,
      backgroundColor: '#C91D24',
      alignItems: 'center',
      justifyContent: 'center',
    },
    saveButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
      textAlign: 'center',
    },
  });
};

export default createStyles;
