import {StyleSheet} from 'react-native';

import type {DesignSystem} from 'theme/designSystem';

type Args = {
  design: DesignSystem;
  isWide: boolean;
};

const createStyles = ({design, isWide}: Args) => {
  const {spacing, radius, font, safeArea, control} = design;

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: '#050506',
      paddingTop: safeArea.top + spacing.sm,
      paddingBottom: safeArea.bottom + spacing.sm,
      paddingHorizontal: spacing.md,
    },
    glowTop: {
      position: 'absolute',
      top: -140,
      right: -120,
      width: 320,
      height: 320,
      borderRadius: 160,
      backgroundColor: 'rgba(201,29,36,0.16)',
    },
    glowBottom: {
      position: 'absolute',
      bottom: -180,
      left: -140,
      width: 360,
      height: 360,
      borderRadius: 180,
      backgroundColor: 'rgba(255,255,255,0.035)',
    },
    header: {
      minHeight: control.headerHeight,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderRadius: radius.xl,
      backgroundColor: 'rgba(14,14,18,0.94)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      marginBottom: spacing.md,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      minWidth: 0,
    },
    logo: {
      width: isWide ? 54 : 42,
      height: isWide ? 54 : 42,
      marginRight: spacing.sm,
    },
    eyebrow: {
      color: '#E53A42',
      fontSize: font.small,
      fontWeight: '800',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    headerTitle: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
    },
    headerMeta: {
      color: 'rgba(255,255,255,0.56)',
      fontSize: font.small,
      marginTop: 2,
    },
    logoutButton: {
      minHeight: control.minTouch,
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(229,58,66,0.42)',
      backgroundColor: 'rgba(201,29,36,0.14)',
      marginLeft: spacing.sm,
    },
    logoutText: {
      color: '#FFFFFF',
      fontWeight: '800',
      fontSize: font.body,
    },
    body: {
      flex: 1,
      flexDirection: isWide ? 'row' : 'column',
      gap: spacing.md,
    },
    sidebar: {
      width: isWide ? 250 : '100%',
      flexShrink: 0,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(12,12,15,0.96)',
      padding: spacing.sm,
      flexDirection: isWide ? 'column' : 'row',
      alignItems: isWide ? 'stretch' : 'center',
      gap: spacing.sm,
    },
    sidebarHeader: {
      padding: spacing.sm,
      minWidth: isWide ? undefined : 120,
    },
    sidebarTitle: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    sidebarHint: {
      color: 'rgba(255,255,255,0.48)',
      fontSize: font.small,
      marginTop: 2,
    },
    sidebarItem: {
      minHeight: control.buttonHeight,
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.06)',
      backgroundColor: 'rgba(255,255,255,0.04)',
      paddingHorizontal: spacing.sm,
      flex: isWide ? undefined : 1,
    },
    sidebarItemActive: {
      borderColor: 'rgba(229,58,66,0.46)',
      backgroundColor: 'rgba(201,29,36,0.18)',
    },
    sidebarIcon: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: 'rgba(255,255,255,0.08)',
      color: '#FFFFFF',
      textAlign: 'center',
      textAlignVertical: 'center',
      fontWeight: '900',
      marginRight: spacing.sm,
    },
    sidebarIconActive: {
      backgroundColor: '#C91D24',
    },
    sidebarTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    sidebarLabel: {
      color: 'rgba(255,255,255,0.78)',
      fontSize: font.body,
      fontWeight: '800',
    },
    sidebarLabelActive: {
      color: '#FFFFFF',
    },
    sidebarItemHint: {
      color: 'rgba(255,255,255,0.42)',
      fontSize: font.small,
      marginTop: 2,
    },
    contentPanel: {
      flex: 1,
      minWidth: 0,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(9,9,12,0.92)',
      overflow: 'hidden',
    },
    contentScroll: {
      flex: 1,
    },
    contentScrollBody: {
      padding: spacing.md,
      paddingBottom: spacing.xl,
    },
    kpiRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginBottom: spacing.md,
    },
    kpiCard: {
      minWidth: isWide ? 150 : '47%',
      flexGrow: 1,
      padding: spacing.md,
      borderRadius: radius.lg,
      backgroundColor: 'rgba(255,255,255,0.055)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    kpiValue: {
      color: '#FFFFFF',
      fontSize: font.titleLarge,
      fontWeight: '900',
    },
    kpiLabel: {
      color: 'rgba(255,255,255,0.54)',
      fontSize: font.small,
      marginTop: 4,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: spacing.sm,
      marginBottom: spacing.md,
      flexWrap: 'wrap',
    },
    sectionTitle: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
    },
    sectionHint: {
      color: 'rgba(255,255,255,0.52)',
      fontSize: font.body,
      marginTop: 4,
      maxWidth: 720,
    },
    filterWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
      marginBottom: spacing.md,
    },
    filterChip: {
      minHeight: control.minTouch,
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.04)',
    },
    filterChipActive: {
      borderColor: 'rgba(229,58,66,0.5)',
      backgroundColor: 'rgba(201,29,36,0.22)',
    },
    filterText: {
      color: 'rgba(255,255,255,0.68)',
      fontWeight: '800',
      fontSize: font.body,
    },
    filterTextActive: {
      color: '#FFFFFF',
    },
    orderGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.md,
    },
    orderCard: {
      width: isWide ? '48.5%' : '100%',
      minWidth: isWide ? 360 : undefined,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.09)',
      backgroundColor: 'rgba(18,18,22,0.98)',
      padding: spacing.md,
    },
    orderHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: spacing.sm,
    },
    orderTitleBlock: {
      flex: 1,
      minWidth: 0,
    },
    orderCode: {
      color: 'rgba(255,255,255,0.48)',
      fontSize: font.small,
      fontWeight: '700',
    },
    orderTable: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
      marginTop: 2,
    },
    orderTime: {
      color: 'rgba(255,255,255,0.5)',
      fontSize: font.small,
      marginTop: 3,
    },
    orderBadgeColumn: {
      alignItems: 'flex-end',
      gap: spacing.xs,
    },
    badge: {
      borderWidth: 1,
      borderRadius: radius.pill,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xxs,
    },
    badgeText: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
    },
    orderNote: {
      color: 'rgba(255,255,255,0.68)',
      fontSize: font.body,
      marginTop: spacing.sm,
      padding: spacing.sm,
      borderRadius: radius.md,
      backgroundColor: 'rgba(255,255,255,0.04)',
    },
    orderItems: {
      marginTop: spacing.sm,
      gap: spacing.xs,
    },
    orderItemRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: spacing.sm,
    },
    orderItemName: {
      color: '#FFFFFF',
      fontSize: font.body,
      flex: 1,
      minWidth: 0,
    },
    orderItemPrice: {
      color: 'rgba(255,255,255,0.64)',
      fontSize: font.body,
      fontWeight: '800',
    },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderTopWidth: 1,
      borderTopColor: 'rgba(255,255,255,0.08)',
      marginTop: spacing.sm,
      paddingTop: spacing.sm,
    },
    totalLabel: {
      color: 'rgba(255,255,255,0.55)',
      fontSize: font.body,
    },
    totalValue: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    actionLabel: {
      color: 'rgba(255,255,255,0.55)',
      fontSize: font.small,
      fontWeight: '800',
      marginTop: spacing.sm,
      marginBottom: spacing.xs,
    },
    actionChipWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
    },
    actionChip: {
      minHeight: 34,
      paddingHorizontal: spacing.sm,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.04)',
    },
    actionChipActive: {
      borderColor: 'rgba(229,58,66,0.5)',
      backgroundColor: 'rgba(201,29,36,0.22)',
    },
    paymentChipActive: {
      borderColor: 'rgba(60,210,150,0.38)',
      backgroundColor: 'rgba(9,168,107,0.20)',
    },
    actionChipText: {
      color: 'rgba(255,255,255,0.65)',
      fontSize: font.small,
      fontWeight: '800',
    },
    actionChipTextActive: {
      color: '#FFFFFF',
    },
    sectionHeaderActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      alignItems: 'center',
      gap: spacing.xs,
    },
    headerSecondaryButton: {
      minHeight: control.buttonHeight,
      paddingHorizontal: spacing.md,
      borderRadius: radius.pill,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
      backgroundColor: 'rgba(255,255,255,0.06)',
    },
    headerSecondaryButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    primaryButton: {
      minHeight: control.buttonHeight,
      paddingHorizontal: spacing.md,
      borderRadius: radius.pill,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#C91D24',
    },
    primaryButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    grid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.md,
    },
    menuCard: {
      width: isWide ? '31.8%' : '100%',
      minWidth: isWide ? 260 : undefined,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.09)',
      backgroundColor: 'rgba(18,18,22,0.98)',
      overflow: 'hidden',
    },
    menuThumb: {
      width: '100%',
      height: isWide ? 130 : 150,
      backgroundColor: 'rgba(255,255,255,0.07)',
    },
    menuInfo: {
      padding: spacing.md,
    },
    menuName: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    menuMeta: {
      color: 'rgba(255,255,255,0.52)',
      fontSize: font.small,
      marginTop: 4,
    },
    priceText: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
      marginTop: spacing.xs,
    },
    statusPill: {
      alignSelf: 'flex-start',
      borderWidth: 1,
      borderRadius: radius.pill,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xxs,
      marginTop: spacing.xs,
    },
    statusPillText: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
    },
    secondaryButton: {
      minHeight: control.minTouch,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(229,58,66,0.38)',
      marginTop: spacing.sm,
    },
    secondaryButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: spacing.xxl,
      paddingHorizontal: spacing.md,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.035)',
    },
    emptyIcon: {
      fontSize: 38,
      marginBottom: spacing.xs,
    },
    emptyText: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
      textAlign: 'center',
    },
    emptySubText: {
      color: 'rgba(255,255,255,0.52)',
      fontSize: font.body,
      textAlign: 'center',
      marginTop: spacing.xs,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.72)',
      alignItems: 'center',
      justifyContent: 'center',
      padding: spacing.md,
    },
    editModalCard: {
      width: '100%',
      maxWidth: 720,
      maxHeight: '92%',
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
      backgroundColor: '#111116',
      padding: spacing.md,
    },
    editModalHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: spacing.md,
      gap: spacing.sm,
    },
    editModalTitle: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
    },
    editModalHint: {
      color: 'rgba(255,255,255,0.48)',
      fontSize: font.small,
      marginTop: 4,
    },
    modalCloseButton: {
      width: control.minTouch,
      height: control.minTouch,
      borderRadius: radius.pill,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.08)',
    },
    modalCloseText: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
    },
    imagePickerCard: {
      flexDirection: isWide ? 'row' : 'column',
      gap: spacing.md,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(255,255,255,0.045)',
      padding: spacing.sm,
    },
    imagePickerPreview: {
      width: isWide ? 170 : '100%',
      height: isWide ? 126 : 168,
      borderRadius: radius.lg,
      backgroundColor: 'rgba(255,255,255,0.07)',
      overflow: 'hidden',
    },
    imagePickerPlaceholder: {
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: 'rgba(255,255,255,0.16)',
    },
    imagePickerPlaceholderText: {
      color: 'rgba(255,255,255,0.46)',
      fontSize: font.body,
      fontWeight: '800',
    },
    imagePickerInfo: {
      flex: 1,
      minWidth: 0,
      justifyContent: 'center',
    },
    imagePickerTitle: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    imagePickerHint: {
      color: 'rgba(255,255,255,0.50)',
      fontSize: font.small,
      marginTop: spacing.xs,
    },
    imagePickerButtonRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
      marginTop: spacing.sm,
    },
    imagePickerButton: {
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      backgroundColor: '#C91D24',
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    imagePickerButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    imageRemoveButton: {
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    imageRemoveButtonText: {
      color: 'rgba(255,255,255,0.82)',
      fontSize: font.body,
      fontWeight: '800',
    },
    categoryManagerCard: {
      width: '100%',
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
      backgroundColor: 'rgba(18,18,22,0.98)',
      padding: spacing.md,
    },
    categoryFormRow: {
      flexDirection: isWide ? 'row' : 'column',
      alignItems: isWide ? 'flex-end' : 'stretch',
      gap: spacing.sm,
      marginTop: spacing.md,
    },
    categoryInputColumn: {
      flex: 1,
      minWidth: isWide ? 320 : undefined,
    },
    categoryList: {
      marginTop: spacing.md,
      gap: spacing.sm,
    },
    categoryRow: {
      flexDirection: isWide ? 'row' : 'column',
      alignItems: isWide ? 'center' : 'stretch',
      justifyContent: 'space-between',
      gap: spacing.sm,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.045)',
      padding: spacing.sm,
    },
    categoryRowActive: {
      borderColor: 'rgba(229,58,66,0.46)',
      backgroundColor: 'rgba(201,29,36,0.16)',
    },
    categoryInfo: {
      flex: 1,
      minWidth: 0,
    },
    categoryName: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    categoryMeta: {
      color: 'rgba(255,255,255,0.48)',
      fontSize: font.small,
      marginTop: 3,
      fontWeight: '700',
    },
    categoryActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      gap: spacing.xs,
    },
    dangerButton: {
      minHeight: control.buttonHeight,
      paddingHorizontal: spacing.md,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,105,105,0.42)',
      backgroundColor: 'rgba(255,75,75,0.14)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    dangerButtonText: {
      color: '#FFB3B3',
      fontSize: font.body,
      fontWeight: '900',
    },
    inputLabel: {
      color: 'rgba(255,255,255,0.75)',
      fontSize: font.small,
      fontWeight: '900',
      marginBottom: spacing.xs,
      marginTop: spacing.sm,
    },
    adminInput: {
      minHeight: control.fieldHeight,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(255,255,255,0.055)',
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      paddingHorizontal: spacing.md,
    },
    adminInputButton: {
      justifyContent: 'center',
      paddingVertical: spacing.sm,
    },
    adminInputValueText: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '800',
    },
    adminInputPlaceholderText: {
      color: 'rgba(255,255,255,0.36)',
      fontSize: font.bodyLarge,
      fontWeight: '700',
    },
    adminTextArea: {
      minHeight: 96,
      paddingTop: spacing.sm,
      textAlignVertical: 'top',
    },
    categoryPickerWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
    },
    categoryPickChip: {
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(255,255,255,0.05)',
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    categoryPickChipActive: {
      borderColor: 'rgba(229,58,66,0.48)',
      backgroundColor: 'rgba(201,29,36,0.20)',
    },
    categoryPickText: {
      color: 'rgba(255,255,255,0.65)',
      fontSize: font.body,
      fontWeight: '800',
    },
    categoryPickTextActive: {
      color: '#FFFFFF',
    },
    formError: {
      color: '#FF7777',
      fontSize: font.body,
      fontWeight: '800',
      marginTop: spacing.sm,
    },
    editModalFooter: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: spacing.sm,
      borderTopWidth: 1,
      borderTopColor: 'rgba(255,255,255,0.08)',
      marginTop: spacing.md,
      paddingTop: spacing.md,
    },
    cancelButton: {
      minHeight: control.buttonHeight,
      paddingHorizontal: spacing.md,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cancelButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '800',
    },
    saveButton: {
      minHeight: control.buttonHeight,
      paddingHorizontal: spacing.lg,
      borderRadius: radius.pill,
      backgroundColor: '#C91D24',
      alignItems: 'center',
      justifyContent: 'center',
    },
    saveButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
  });
};

export default createStyles;
